// Code generated by cmd/reset. DO NOT EDIT.

package testdata

func (r *ResetableStruct) Reset() {
	if r == nil {
		return
	}

	r.I = 0

	r.Str = ""

	if r.StrP != nil {
		*r.StrP = ""
	}

	r.S = r.S[:0]

	clear(r.M)

	if r.Child != nil {
		if resetter, ok := interface{}(r.Child).(interface{ Reset() }); ok {
			resetter.Reset()
		} else {
			*r.Child = ResetableStruct{}
		}
	}

}
