package generator

import (
	"fmt"
	"go/ast"
	"go/format"
	"os"
	"strings"
)

// PackageInfo содержит информацию о пакете и его структурах
type PackageInfo struct {
	Name    string
	Structs []*StructInfo
}

// StructInfo содержит информацию о структуре
type StructInfo struct {
	Name   string
	Fields []*FieldInfo
}

// FieldInfo содержит информацию о поле структуры
type FieldInfo struct {
	Name string
	Type FieldType
}

// FieldType представляет тип поля
type FieldType struct {
	BaseType    string // int, string, []int, map[string]string, *int, и т.д.
	IsPointer   bool
	IsSlice     bool
	IsMap       bool
	IsStruct    bool
	ElementType string // для слайсов и мапов
	KeyType     string // для мапов
}

// GetFieldType определяет тип поля из AST узла
func GetFieldType(expr ast.Expr) FieldType {
	ft := FieldType{}

	switch t := expr.(type) {
	case *ast.Ident:
		ft.BaseType = t.Name
		ft.IsStruct = isStructType(t.Name)

	case *ast.SelectorExpr:
		ft.BaseType = fmt.Sprintf("%s.%s", t.X.(*ast.Ident).Name, t.Sel.Name)
		ft.IsStruct = true

	case *ast.ArrayType:
		ft.IsSlice = true
		if t.Len == nil {
			// []T
			ft.BaseType = fmt.Sprintf("[]%s", getTypeString(t.Elt))
			ft.ElementType = getTypeString(t.Elt)
		} else {
			// [N]T
			ft.BaseType = fmt.Sprintf("[%s]%s", getTypeString(t.Len), getTypeString(t.Elt))
			ft.ElementType = getTypeString(t.Elt)
		}

	case *ast.MapType:
		ft.IsMap = true
		ft.KeyType = getTypeString(t.Key)
		ft.ElementType = getTypeString(t.Value)
		ft.BaseType = fmt.Sprintf("map[%s]%s", ft.KeyType, ft.ElementType)

	case *ast.StarExpr:
		ft.IsPointer = true
		innerType := GetFieldType(t.X)
		ft.BaseType = "*" + innerType.BaseType
		ft.ElementType = innerType.BaseType
		ft.IsStruct = innerType.IsStruct
		ft.IsSlice = innerType.IsSlice
		ft.IsMap = innerType.IsMap
		ft.KeyType = innerType.KeyType

	case *ast.ChanType:
		ft.BaseType = fmt.Sprintf("chan %s", getTypeString(t.Value))

	case *ast.InterfaceType:
		ft.BaseType = "interface{}"

	default:
		ft.BaseType = getTypeString(expr)
	}

	return ft
}

func getTypeString(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.SelectorExpr:
		return fmt.Sprintf("%s.%s", t.X.(*ast.Ident).Name, t.Sel.Name)
	case *ast.ArrayType:
		if t.Len == nil {
			return fmt.Sprintf("[]%s", getTypeString(t.Elt))
		}
		return fmt.Sprintf("[%s]%s", getTypeString(t.Len), getTypeString(t.Elt))
	case *ast.StarExpr:
		return "*" + getTypeString(t.X)
	case *ast.MapType:
		return fmt.Sprintf("map[%s]%s", getTypeString(t.Key), getTypeString(t.Value))
	default:
		return "unknown"
	}
}

func isStructType(name string) bool {
	// Базовые типы Go не являются структурами
	primitives := map[string]bool{
		"int": true, "int8": true, "int16": true, "int32": true, "int64": true,
		"uint": true, "uint8": true, "uint16": true, "uint32": true, "uint64": true,
		"float32": true, "float64": true,
		"complex64": true, "complex128": true,
		"byte": true, "rune": true,
		"string": true, "bool": true,
		"error": true,
	}
	return !primitives[name]
}

func isStructTypeName(name string) bool {
	// Убираем префиксы типа [] или map[...]
	cleanName := strings.TrimPrefix(name, "[]")
	if idx := strings.Index(cleanName, "]"); idx != -1 {
		cleanName = cleanName[idx+1:]
	}
	if idx := strings.Index(cleanName, "["); idx != -1 {
		cleanName = cleanName[:idx]
	}
	// Убираем указатели
	cleanName = strings.TrimPrefix(cleanName, "*")
	// Убираем квалификаторы пакетов
	if idx := strings.LastIndex(cleanName, "."); idx != -1 {
		cleanName = cleanName[idx+1:]
	}
	return isStructType(cleanName)
}

// GenerateResetFile генерирует файл reset.gen.go для пакета
func GenerateResetFile(pkgPath string, pkgInfo *PackageInfo) error {
	var sb strings.Builder

	// Заголовок файла
	sb.WriteString("// Code generated by cmd/reset. DO NOT EDIT.\n\n")
	sb.WriteString(fmt.Sprintf("package %s\n\n", pkgInfo.Name))

	// Генерируем методы Reset() для каждой структуры
	for _, structInfo := range pkgInfo.Structs {
		sb.WriteString(generateResetMethod(structInfo))
		sb.WriteString("\n\n")
	}

	// Форматируем код
	formatted, err := format.Source([]byte(sb.String()))
	if err != nil {
		return fmt.Errorf("failed to format generated code: %w", err)
	}

	// Записываем в файл
	filePath := fmt.Sprintf("%s/reset.gen.go", pkgPath)
	if err := os.WriteFile(filePath, formatted, 0644); err != nil {
		return fmt.Errorf("failed to write file: %w", err)
	}

	return nil
}

// generateResetMethod генерирует метод Reset() для структуры
func generateResetMethod(structInfo *StructInfo) string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("func (r *%s) Reset() {\n", structInfo.Name))
	sb.WriteString("\tif r == nil {\n")
	sb.WriteString("\t\treturn\n")
	sb.WriteString("\t}\n\n")

	for _, field := range structInfo.Fields {
		if field.Name == "" {
			// Анонимное поле - пропускаем или обрабатываем отдельно
			continue
		}

		sb.WriteString(generateFieldReset(field))
		sb.WriteString("\n")
	}

	sb.WriteString("}")

	return sb.String()
}

// generateFieldReset генерирует код сброса для поля
func generateFieldReset(field *FieldInfo) string {
	var sb strings.Builder

	fieldName := fmt.Sprintf("r.%s", field.Name)

	if field.Type.IsPointer {
		// Указатель
		sb.WriteString(fmt.Sprintf("\tif %s != nil {\n", fieldName))

		// Определяем внутренний тип (без указателя)
		innerBaseType := strings.TrimPrefix(field.Type.ElementType, "*")
		innerType := FieldType{
			BaseType: innerBaseType,
			IsSlice:  strings.HasPrefix(innerBaseType, "[]"),
			IsMap:    strings.HasPrefix(innerBaseType, "map["),
			IsStruct: field.Type.IsStruct || isStructTypeName(innerBaseType),
		}

		if innerType.IsSlice {
			sb.WriteString(fmt.Sprintf("\t\t%s = %s[:0]\n", fieldName, fieldName))
		} else if innerType.IsMap {
			sb.WriteString(fmt.Sprintf("\t\tclear(%s)\n", fieldName))
		} else if innerType.IsStruct {
			// Для указателя на структуру вызываем Reset() если есть, иначе создаем новую структуру
			structName := getStructNameFromType(innerType.BaseType)
			sb.WriteString(fmt.Sprintf("\t\tif resetter, ok := interface{}(%s).(interface{ Reset() }); ok {\n", fieldName))
			sb.WriteString("\t\t\tresetter.Reset()\n")
			sb.WriteString("\t\t} else {\n")
			sb.WriteString(fmt.Sprintf("\t\t\t*%s = %s{}\n", fieldName, structName))
			sb.WriteString("\t\t}\n")
		} else {
			// Примитивный тип
			zeroValue := getZeroValue(innerType.BaseType)
			sb.WriteString(fmt.Sprintf("\t\t*%s = %s\n", fieldName, zeroValue))
		}

		sb.WriteString("\t}\n")
	} else if field.Type.IsSlice {
		// Слайс
		sb.WriteString(fmt.Sprintf("\t%s = %s[:0]\n", fieldName, fieldName))
	} else if field.Type.IsMap {
		// Мапа
		sb.WriteString(fmt.Sprintf("\tclear(%s)\n", fieldName))
	} else if field.Type.IsStruct {
		// Структура - вызываем Reset() если есть, иначе создаем новую структуру
		structName := getStructNameFromType(field.Type.BaseType)
		sb.WriteString(fmt.Sprintf("\tif resetter, ok := interface{}(&%s).(interface{ Reset() }); ok {\n", fieldName))
		sb.WriteString("\t\tresetter.Reset()\n")
		sb.WriteString("\t} else {\n")
		sb.WriteString(fmt.Sprintf("\t\t%s = %s{}\n", fieldName, structName))
		sb.WriteString("\t}\n")
	} else {
		// Примитивный тип
		zeroValue := getZeroValue(field.Type.BaseType)
		sb.WriteString(fmt.Sprintf("\t%s = %s\n", fieldName, zeroValue))
	}

	return sb.String()
}

func getStructNameFromType(typeStr string) string {
	// Убираем указатели и получаем имя структуры
	typeStr = strings.TrimPrefix(typeStr, "*")
	// Убираем префиксы слайсов и мапов
	typeStr = strings.TrimPrefix(typeStr, "[]")
	if idx := strings.Index(typeStr, "]"); idx != -1 {
		typeStr = typeStr[idx+1:]
	}
	if idx := strings.Index(typeStr, "["); idx != -1 {
		typeStr = typeStr[:idx]
	}
	// Возвращаем как есть (может быть с квалификатором пакета)
	return typeStr
}

func getZeroValue(typeStr string) string {
	// Убираем указатели для определения базового типа
	baseType := strings.TrimPrefix(typeStr, "*")

	switch baseType {
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64",
		"float32", "float64",
		"complex64", "complex128",
		"byte", "rune":
		return "0"
	case "string":
		return `""`
	case "bool":
		return "false"
	case "error":
		return "nil"
	default:
		return fmt.Sprintf("%s{}", baseType)
	}
}
